baseURL = 'https://pierrick-marie.github.io/'
languageCode = 'fr-FR'
title = 'Développeur informatique freelance'
theme = 'yummy-yam'

disableKinds = ["taxonomy", "term", "RSS"]

enableRobotsTXT = true

contentDir = 'content'

[params]
	author = "Pierrick MARIE"
	subtitle = "Voyageur au long court"
	description = "Freelance développeur informatique Pierrick MARIE : projets, technologies et contacts."
	keywords = "freelance, java, kotlin, springBoot, rust"

[menu]
	[[menu.main]]
		name = 'Home'
		pre = 'home'
		url = '/'
		weight = 1
	[[menu.main]]
    		name = "Posts"
    		pre = "posts"
    		url = "/posts/"
    		weight = 2

[module]
	[[module.mounts]]
      	source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      	target = "assets/js/bootstrap/bundle.min.js"

[sitemap]
	changefreq = 'monthly'
	filename = 'sitemap.xml'
