baseURL = 'https://pierrick-marie.github.io/'
languageCode = 'fr-FR'
title = 'Développeur informatique freelance'
theme = 'yummy-yam'

disableKinds = ["taxonomy", "term", "RSS"]

enableRobotsTXT = true

contentDir = 'content'

[params]
	author = "Pierrick MARIE"
	subtitle = "Voyageur au long court"
	description = "Freelance développeur informatique Pierrick MARIE : projets, technologies et contacts."
	keywords = "freelance, java, kotlin, springBoot, rust"
	footer = "© Tous droits réservés - Pierrick MARIE - 2023"
	customCSS = [ "simple-gallery.css" ]
	customJS = [ "simple-gallery.js" ]

[menu]
	[[menu.main]]
		name = 'Home'
		pre = 'home'
		url = '/'
		weight = 1
	[[menu.main]]
    		name = "Posts"
    		pre = "posts"
    		url = "/posts/"
    		weight = 2

[sitemap]
	changefreq = 'monthly'
	filename = 'sitemap.xml'
